- name: Install vcpkg build dependencies
  run: sudo apt-get --assume-yes install nasm

- name: Install vcpkg
  run: cargo install cargo-vcpkg

- name: Build vcpkg dependencies
  run: cargo vcpkg --verbose build
